#####################################################
# Loads default set of integrations.
default_config:
homeassistant:
  media_dirs: 
    media: /config/www/media
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - !secret trusted_network_1
        - !secret trusted_network_2
        - !secret trusted_network_3
        - !secret trusted_network_4
  external_url: !secret external_url
  internal_url: !secret internal_url
  allowlist_external_dirs:
    - /config/www/
    - /config/www/media/

logger:
  default: info

#####################################################
# ssl etc...
http:
  use_x_forwarded_for: true
  trusted_proxies:
  - 172.30.33.0/24

#####################################################
# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

#####################################################
# Includes
automation: !include automations.yaml
scene: !include .includes/scene.yaml
mqtt: !include .includes/mqtt.yaml
template: !include .includes/template.yaml
sensor: !include .includes/sensor.yaml
shell_command: !include .includes/shell_commands.yaml
