#####################################################
# Loads default set of integrations.
default_config:
logger:
  default: info

#####################################################
# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

#####################################################
# Includes
automation: !include automations.yaml
group: !include .includes/group.yaml
homeassistant: !include .includes/homeassistant.yaml
http: !include .includes/http.yaml
influxdb: !include .includes/influxdb.yaml
mqtt:
  switch: !include_dir_merge_list .includes/mqtt/switch
  sensor: !include_dir_merge_list .includes/mqtt/sensor
  binary_sensor: !include_dir_merge_list .includes/mqtt/binary_sensor
sensor: !include .includes/sensor.yaml
shell_command: !include .includes/shell_command.yaml
template: !include .includes/template.yaml
utility_meter: !include .includes/utility_meter.yaml
