esp32_ble_tracker:
  scan_parameters:
    active: true
    interval: 320ms
    window: 30ms

binary_sensor:
  - platform: ble_presence
    mac_address: "A4:75:B9:52:F6:35"
    name: "Samsung S22"
    device_class: presence
  - platform: ble_presence
    mac_address: "A4:75:B9:52:F6:35"
    name: "Samsung A35"
    device_class: presence
  - platform: ble_presence
    mac_address: "B0:D5:FB:D1:11:50"
    name: "Pixel 10 Pro"
    device_class: presence