esp32_ble_tracker:
  scan_parameters:
    active: true
    interval: 320ms
    window: 30ms

binary_sensor:
  - platform: ble_presence
    mac_address: "A4:75:B9:52:F6:35"
    name: "kjell_mobil"
    device_class: presence
  - platform: ble_presence
    mac_address: "A4:75:B9:52:F6:35"
    name: "bettan_mobil"
    device_class: presence