#####################################################
# Common misc
default_config:

homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - !secret trusted_network_1
        - !secret trusted_network_2
        - !secret trusted_network_3
        - !secret trusted_network_4
  external_url: !secret external_url
  internal_url: !secret internal_url

#####################################################
# ssl etc
http:
  use_x_forwarded_for: true
  trusted_proxies:
  - 172.30.33.0/24

#####################################################
# Includes
automation: !include automations.yaml
scene: !include scenes.yaml
input_boolean: !include .includes/input_boolean.yaml
binary_sensor: !include .includes/binary_sensor.yaml
template: !include .includes/template.yaml
mqtt:
  switch: !include_dir_merge_list .includes/mqtt/switch
  sensor: !include_dir_merge_list .includes/mqtt/sensor
shell_command: !include .includes/shell_command.yaml
sensor: !include .includes/sensor.yaml




