#######################################################
esphome:
  name: pumptemp
  friendly_name: PumpTemp

esp8266:
  board: esp01_1m

packages:
  network: !include common/network.yaml
  system: !include common/system.yaml
  firmware: !include common/firmware.yaml
#######################################################
# GLOBALS
globals:
  - id: fw_version
    type: std::string
    restore_value: no
    initial_value: "\"v1.2\""
#######################################################

one_wire:
  - platform: gpio
    pin: GPIO14

sensor:
  - platform: dallas_temp
    address: 0xC53CE10457C6C928
    name: "heatpump_primary_in"
  - platform: dallas_temp
    address: 0x483CE10457B53D28
    name: "heatpump_primary_out"
  - platform: dallas_temp
    address: 0x483CE10457891328
    name: "heatpump_secondary_out"
  - platform: dallas_temp
    address: 0x5C3CE104574DF328
    name: "heatpump_secondary_in"
